name: petcard
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  http: ^1.5.0
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  supabase_flutter: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: "^2.3.0"
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#2563EB"
  image: assets/icon/logo.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/icon/